Repository FACG6/social-streets, pull requests merged in 2019-06, with the labels that each got.

#50 Create Profile
  client/src/components/pages/createProfile/index.js
  client/src/components/pages/createProfile/style.css
  client/src/components/utils/businessForm/business-type.js
  client/src/components/utils/businessForm/country.json
  client/src/components/utils/businessForm/index.js
  client/src/components/utils/businessForm/style.css
  client/src/components/utils/personalForm/index.js
  client/src/components/utils/personalForm/style.css
Labels: Done

#40 Login Page | Route
  client/src/components/pages/Login/index.js
  client/src/components/pages/Login/style.css
Labels: Awaiting Review

#64 refactor button component
  client/src/components/pages/CreatePostPage/Event/index.js
  client/src/components/pages/CreatePostPage/PublicServices/index.js
  client/src/components/pages/Home/index.js
  client/src/components/utils/Button/index.js
  client/src/components/utils/businessForm/index.js
  client/src/components/utils/personalForm/index.js
Labels: Awaiting Review, Urgent, bug

#62 Edit Babel Configuration
  client/config-overrides.js
  client/package-lock.json
  client/package.json
  client/src/components/app/App.js
Labels: Awaiting Review, enhancement

#59 Edit Page
  client/package.json
  client/src/components/pages/PostForm/Event/index.js
  client/src/components/pages/PostForm/Event/style.css
  client/src/components/pages/PostForm/PublicServices/index.js
  client/src/components/pages/PostForm/PublicServices/style.css
  client/src/components/pages/PostForm/dumyData.js
  client/src/components/pages/PostForm/index.js
  client/src/components/pages/PostForm/style.css
  client/src/components/pages/index.js
Labels: Awaiting Review, F.E.Route, Frontend

#66 fix conflict Edit Page
  client/src/components/pages/PostForm/Event/index.js
  client/src/components/pages/PostForm/PublicServices/index.js
Labels: Urgent, bug

#63 create the personal info form for the profile page
  client/src/assets/profile-pic.jpg
  client/src/components/utils/ProfilePersonal/index.js
  client/src/components/utils/ProfilePersonal/style.css
Labels: Awaiting Review

#58 Post page
  client/src/components/pages/Post/index.js
  client/src/components/pages/Post/postDetails.js
  client/src/components/pages/Post/style.css
  client/src/components/utils/PostButton/index.js
  client/src/components/utils/PostButton/style.css
  client/src/components/utils/PostRow/index.js
  client/src/components/utils/PostRow/style.css
Labels: Awaiting Review

#52 Event Page
  client/src/components/pages/Event/index.js
  client/src/components/pages/Event/staticData.js
  client/src/components/pages/Event/style.css
  client/src/components/utils/index.js
Labels: Awaiting Review

#67 Edit Event Page
  client/src/components/pages/Event/index.js
Labels: Done

#60 Public Service Page
  client/src/components/pages/PublicService/dummyData.js
  client/src/components/pages/PublicService/index.js
  client/src/components/pages/PublicService/style.css
Labels: Awaiting Review

#68 Edit the social inputs
  client/src/components/utils/businessForm/index.js
Labels: Awaiting Review, bug

#51 Edit app
  client/src/components/app/App.css
  client/src/components/app/App.js
  client/src/components/pages/Home/style.css
  client/src/components/pages/Login/index.js
  client/src/components/pages/PageNotFound/style.css
  client/src/components/pages/index.js
  client/src/components/utils/footer/style.css
  client/src/components/utils/index.js
Labels: Awaiting Review, Frontend, bug

#87 Server File Structure
  server/.eslintrc.json
  server/.gitignore
  server/app.js
  server/controllers/index.js
  server/controllers/middlewares/.gitkeep
  server/controllers/routes/.gitkeep
  server/controllers/utils/.gitkeep
  server/database/config/.gitkeep
  server/database/queries/.gitkeep
  server/index.js
  server/package-lock.json
  server/package.json
  server/test/queries/.gitkeep
  server/test/routes/.gitkeep
  server/uploads/.gitkeep
Labels: Awaiting Review

#90 add travis config and simple test
  .travis.yml
  server/package.json
  server/test/index.js
Labels: Awaiting Review, Backend

#85 edit schema
  README.md
Labels: Changes Requested

#93 jsconfig Server
  server/jsconfig.json
Labels: Awaiting Review, Backend

#91 Database config
  server/database/config/.gitkeep
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/fakeData.test.sql
  server/database/config/staticData.sql
  server/jsconfig.json
  server/package.json
Labels: Awaiting Review

#98 DB SQL
  server/database/config/build.sql
  server/database/config/fakeData.test.sql
Labels: Awaiting Review

#95 unlockCookie middleware
  server/controllers/middlewares/unlockCookie.js
Labels: Awaiting Review

#105 Add posts at route /post
  server/.eslintrc.json
  server/app.js
  server/controllers/index.js
  server/controllers/routes/index.js
  server/controllers/routes/post/addPost.js
  server/controllers/routes/post/index.js
  server/controllers/utils/postSchema.js
  server/database/queries/postEvent.js
  server/package-lock.json
  server/package.json
  server/test/fakeImg/amideasblue.png
  server/test/index.js
  server/test/queries/insertEvent.js
  server/test/queries/insertPublicServices.js
  server/test/queries/insertSecondaryTag.js
  server/test/queries/insertTopic.js
  server/test/routes/post/post.js
Labels: Awaiting Review, B.E.Route, Backend

#110 Edit some bugs
  server/controllers/index.js
  server/controllers/routes/post/addPost.js
  server/controllers/routes/post/index.js
  server/controllers/routes/post/post.js
  server/controllers/utils/postSchema.js
Labels: Awaiting Review

#108 add route , queries and it testes
  server/controllers/index.js
  server/controllers/middlewares/.gitkeep
  server/controllers/routes/index.js
  server/controllers/routes/post/get.js
  server/controllers/routes/post/index.js
  server/controllers/routes/user/index.js
  server/controllers/routes/user/post.js
  server/controllers/utils/validationSchemes.js
  server/database/queries/getPost.js
  server/test/index.js
  server/test/queries/getEvent.test.js
  server/test/queries/getPublicService.test.js
  server/test/queries/insertUser.test.js
  server/test/routes/fetchPost.test.js
  server/test/routes/userPost.test.js
Labels: Awaiting Review, B.E.Route, Backend

#107 Get draft posts
  server/controllers/routes/post/getDraftPosts.js
  server/controllers/routes/post/index.js
  server/controllers/routes/post/post.js
  server/controllers/utils/postSchema.js
  server/database/queries/getDraftPosts.js
  server/database/queries/postEvent.js
  server/test/index.js
  server/test/queries/getDraftEvents.js
  server/test/queries/getDraftPublicServices.js
  server/test/queries/insertEvent.js
  server/test/queries/insertPublicServices.js
  server/test/queries/insertSecondaryTag.js
  server/test/queries/insertTopic.js
  server/test/routes/post/get.js
  server/test/routes/post/post.js
Labels: Awaiting Review, B.E.Route, Backend

#115 fix bug | ClearCookie
  server/controllers/middlewares/unlockCookie.js
Labels: Done

#113 Async bug
  server/controllers/routes/post/getDraftPosts.js
  server/controllers/routes/post/index.js
  server/controllers/routes/post/post.js
  server/database/queries/getDraftPosts.js
  server/test/queries/getDraftEvents.js
  server/test/queries/getDraftPublicServices.js
  server/test/routes/post/get.js
Labels: bug

#99 Login route | POST
  server/controllers/index.js
  server/controllers/routes/index.js
  server/controllers/routes/login.js
  server/controllers/utils/helper.js
  server/controllers/utils/loginSchema.js
  server/controllers/utils/validationSchemes.js
  server/database/queries/getUser.js
  server/test/index.js
  server/test/queries/getUser.test.js
  server/test/routes/login.test.js
Labels: Awaiting Review

#96 User Route | Get
  server/controllers/middlewares/unlockCookie.js
  server/controllers/routes/login.js
  server/controllers/routes/user/get.js
  server/controllers/routes/user/index.js
  server/database/queries/getUser.js
  server/test/index.js
  server/test/queries/getUser.test.js
  server/test/routes/getUser.js
Labels: Awaiting Review

#118 add axios for front sign-up
  client/src/components/pages/createProfile/index.js
  client/src/components/utils/businessForm/business-type.js
  client/src/components/utils/businessForm/index.js
  client/src/components/utils/personalForm/index.js
  server/.gitignore
  server/controllers/routes/user/post.js
  server/controllers/utils/validationSchemes.js
  server/database/queries/insertUser.js
  server/test/queries/insertUser.test.js
  server/test/routes/getUser.js
  server/test/routes/userPost.test.js
Labels: Awaiting Review

#124 fix bug with error handling in the login route
  server/controllers/routes/login.js
  server/test/routes/login.test.js
Labels: Awaiting Review

#109 Delete Post
  server/app.js
  server/controllers/routes/post/delete.js
  server/controllers/routes/post/index.js
  server/database/config/build.sql
  server/database/queries/deletePost.js
  server/database/queries/getPostPublisher.js
  server/database/queries/postEvent.js
  server/test/index.js
  server/test/queries/deletePost.js
  server/test/routes/deletePost.js
  server/test/utils/cookies.js
Labels: Awaiting Review

#119 Get Live Posts
  server/controllers/routes/post/getDraftPosts.js
  server/controllers/routes/post/getLivePosts.js
  server/controllers/routes/post/index.js
  server/database/config/fakeData.test.sql
  server/database/queries/getDraftPosts.js
  server/database/queries/getPosts.js
  server/test/index.js
  server/test/queries/getDraftEvents.js
  server/test/queries/getDraftPublicServices.js
  server/test/queries/getLiveEvents.js
  server/test/queries/getLivePublicService.js
  server/test/queries/insertEvent.js
  server/test/routes/getLivePosts.js
  server/test/routes/post/post.js
Labels: Awaiting Review

#128 Get static data
  server/controllers/routes/post/eventStatic.js
  server/controllers/routes/post/index.js
  server/controllers/routes/post/publicServiceStatic.js
  server/database/queries/getEventCategories.js
  server/database/queries/getEventTopics.js
  server/database/queries/getPrimaryTags.js
  server/database/queries/getSecondaryTags.js
Labels: Done

#139 remove unnecessary modules
  client/package-lock.json
  client/package.json
Labels: Awaiting Review

#137 Update Password - Put
  package-lock.json
  server/.gitignore
  server/controllers/routes/post/get.js
  server/controllers/routes/post/post.js
  server/controllers/routes/user/index.js
  server/controllers/routes/user/password.js
  server/controllers/utils/passwordSchema.js
  server/database/queries/getPassword.js
  server/database/queries/updatePassword.js
  server/test/index.js
  server/test/queries/getPassword.test.js
  server/test/queries/updatePassword.test.js
  server/test/routes/passwordPut.test.js
Labels: Awaiting Review

#133 fix bug with navbar
  client/src/components/utils/Header/HamburgerButton/index.js
  client/src/components/utils/Header/Menu/index.js
  client/src/components/utils/Header/index.js
Labels: Awaiting Review, bug

#65 create the profile page component
  client/src/assets/default-profile-pic.jpg
  client/src/components/pages/Profile/ProfilePic/index.js
  client/src/components/pages/Profile/ProfilePic/style.css
  client/src/components/pages/Profile/index.js
  client/src/components/pages/Profile/style.css
  client/src/components/utils/ProfilePersonal/index.js
  client/src/components/utils/ProfilePersonal/style.css
Labels: Awaiting Review, F.E.Route, Frontend

#69 Front-End Routes
  client/src/components/app/App.js
  client/src/components/pages/Event/index.js
  client/src/components/pages/Home/index.js
  client/src/components/pages/Login/index.js
  client/src/components/pages/PostForm/Event/index.js
  client/src/components/pages/PostForm/index.js
  client/src/components/pages/Posts/index.js
  client/src/components/pages/index.js
  client/src/components/utils/Footer/index.js
  client/src/components/utils/Footer/style.css
  client/src/components/utils/Header/Menu/index.js
  client/src/components/utils/Header/Menu/style.css
  client/src/components/utils/Header/index.js
  client/src/components/utils/PostRow/index.js
  client/src/components/utils/index.js
Labels: Awaiting Review, F.E.Routes, Frontend

#116 Edit Post | PUT
  server/.gitignore
  server/controllers/routes/post/delete.js
  server/controllers/routes/post/get.js
  server/controllers/routes/post/index.js
  server/controllers/routes/post/put.js
  server/controllers/utils/postSchema.js
  server/database/config/fakeData.test.sql
  server/database/queries/getPostImg.js
  server/database/queries/getPostPublisher.js
  server/database/queries/updatePost.js
  server/test/index.js
  server/test/queries/getEvent.test.js
  server/test/routes/post/put.test.js
  server/uploads/.gitkeep
  server/uploads/1_profile-pic.jpg
  server/uploads/2_profile-pic.jpg
Labels: Awaiting Review

#130 Posts Component | Axios
  client/src/components/pages/Post/index.js
  client/src/components/utils/PostRow/index.js
  server/controllers/middlewares/unlockCookie.js
  server/controllers/routes/post/getDraftPosts.js
  server/controllers/routes/post/getLivePosts.js
  server/test/routes/getLivePosts.js
Labels: Awaiting Review

#143 140 axios fetch post
  client/src/components/pages/Event/index.js
  client/src/components/pages/Event/style.css
  client/src/components/pages/PublicService/index.js
  client/src/components/pages/PublicService/style.css
  server/app.js
  server/controllers/routes/post/get.js
  server/controllers/routes/user/post.js
  server/database/queries/getPost.js
  server/test/queries/getDraftEvents.js
  server/test/queries/getDraftPublicServices.js
  server/test/queries/getEvent.test.js
  server/test/queries/getLiveEvents.js
  server/test/queries/getPublicService.test.js
  server/test/queries/insertEvent.js
  server/test/queries/insertPublicServices.js
  server/test/queries/insertSecondaryTag.js
  server/test/queries/insertTopic.js
  server/test/routes/fetchPost.test.js
  server/test/routes/post/get.js
  server/test/routes/post/post.js
  server/uploads/3_profile-pic.jpg
Labels: Awaiting Review

#132 send a request to the backend with axios to login the user
  client/src/components/pages/Login/index.js
Labels: Done

#138 Update Personal Details | PUT
  server/controllers/routes/user/index.js
  server/controllers/routes/user/password.js
  server/controllers/routes/user/personal.js
  server/controllers/utils/personalSchema.js
  server/database/queries/updatePersonalData.js
  server/test/index.js
  server/test/queries/updatePersonalDataQuery.test.js
  server/test/routes/personalDataPut.test.js
Labels: Awaiting Review

#146 Authentication Front
  client/src/components/app/App.js
  client/src/components/auth/.gitkeep
  client/src/components/auth/protectedRoute.js
  client/src/components/pages/Loading/index.css
  client/src/components/pages/Loading/index.js
  client/src/components/pages/index.js
  server/controllers/index.js
  server/controllers/routes/isAuth.js
  server/controllers/routes/login.js
  server/controllers/routes/logout.js
Labels: Awaiting Review

#136 123 post fetch
  client/src/components/pages/PostForm/Event/index.js
  client/src/components/pages/PostForm/PublicServices/index.js
  client/src/components/pages/PostForm/dumyData.js
  client/src/components/pages/PostForm/index.js
  client/src/components/utils/DropDownAntd.js
  server/controllers/routes/post/post.js
  server/test/routes/post/post.js
Labels: Awaiting Review

#141 Update Business - Put
  server/controllers/routes/user/business.js
  server/controllers/routes/user/index.js
  server/controllers/routes/user/password.js
  server/controllers/utils/businessSchema.js
  server/database/queries/updateBusinessData.js
  server/test/index.js
  server/test/queries/updateBusinessDataQuery.test.js
  server/test/routes/businessDataPut.test.js
Labels: Awaiting Review

#147 Fetch user info
  client/src/components/pages/PostForm/PublicServices/index.js
  client/src/components/pages/Profile/index.js
  client/src/components/utils/ProfilePersonal/index.js
Labels: Awaiting Review

#165 view posts admin
  client/src/components/app/App.js
  client/src/components/pages/admin/dummy.js
  client/src/components/pages/admin/index.js
  client/src/components/pages/admin/posts/index.css
  client/src/components/pages/admin/posts/index.js
  client/src/components/pages/index.js
  client/src/components/utils/AdminLayout.js
  server/controllers/index.js
  server/controllers/middlewares/authAdmin.js
  server/controllers/routes/admin/getPosts.js
  server/controllers/routes/admin/index.js
  server/controllers/routes/index.js
  server/controllers/routes/login.js
  server/controllers/utils/helper.js
  server/database/config/build.sql
  server/database/queries/getPost.js
Labels: Awaiting Review

#150 Update user info
  client/src/components/app/App.js
  client/src/components/pages/Post/index.js
  client/src/components/pages/PostForm/Event/index.js
  client/src/components/pages/Profile/index.js
  client/src/components/pages/createProfile/index.js
  client/src/components/utils/PostRow/index.js
  client/src/components/utils/PostRow/style.css
  client/src/components/utils/ProfilePersonal/index.js
  client/src/components/utils/businessForm/index.js
  client/src/components/utils/modal.css
  server/controllers/routes/user/business.js
  server/controllers/routes/user/post.js
  server/controllers/utils/businessSchema.js
  server/database/queries/updateBusinessData.js
  server/test/routes/businessDataPut.test.js
Labels: Awaiting Review

#179 Admin Tags
  client/src/components/app/App.js
  client/src/components/auth/protectedRoute.js
  client/src/components/pages/Login/index.js
  client/src/components/pages/admin/Tags/QWE.js
  client/src/components/pages/admin/Tags/index.css
  client/src/components/pages/admin/Tags/index.js
  client/src/components/pages/admin/Tags/style.css
  client/src/components/pages/admin/Tags/tagsSection.js
  client/src/components/pages/member/Profile/ProfilePic/index.js
  client/src/components/routes/unAuth.js
  client/src/components/utils/AdminLayout.js
  client/src/constants/routes.js
  server/controllers/routes/login.js
  server/controllers/routes/post/deleteEventCategory.js
  server/controllers/routes/post/deleteEventTopic.js
  server/controllers/routes/post/deletePublicServicePSecondary.js
  server/controllers/routes/post/deletePublicServicePrimary.js
  server/controllers/routes/post/index.js
  server/controllers/routes/post/postEventCategory.js
  server/controllers/routes/post/postEventTopic.js
  server/controllers/routes/post/postPublicServicePSecondary.js
  server/controllers/routes/post/postPublicServicePrimary.js
  server/controllers/routes/user/index.js
  server/controllers/routes/user/updateProfilePic.js
  server/controllers/utils/helper.js
  server/database/queries/addEventCategory.js
  server/database/queries/addEventTopic.js
  server/database/queries/deleteEventCategory.js
  server/database/queries/deleteEventTopic.js
  server/database/queries/deletePublicPrimary.js
  server/database/queries/deletePublicSecondary.js
  server/database/queries/insertPublicPrimary.js
  server/database/queries/insertPublicSecondary.js
  server/database/queries/updateUserPic.js
Labels: Awaiting Review
