Repository FACG6/social-streets, pull requests merged in 2019-05, with the labels that each got.

#2 Create the documentation
  README.md
Labels: Awaiting Review

#38 File Struture
  client/jsconfig.json
  client/src/App.js
  client/src/assets/.gitkeep
  client/src/components/app/.gitkeep
  client/src/components/auth/.gitkeep
  client/src/components/pages/.gitkeep
  client/src/components/utils/.gitkeep
  client/src/utils/.gitkeep
Labels: Awaiting Review, Frontend

#5 Schema
  README.md
Labels: Awaiting Review

#28 Header component
  client/public/index.html
  client/src/assets/.gitkeep
  client/src/assets/logo.png
  client/src/components/app/App.css
  client/src/components/app/App.js
  client/src/components/utils/.gitkeep
  client/src/components/utils/Header/HamburgerButton/index.js
  client/src/components/utils/Header/HamburgerButton/style.css
  client/src/components/utils/Header/Menu/index.js
  client/src/components/utils/Header/Menu/style.css
  client/src/components/utils/Header/index.js
  client/src/components/utils/Header/style.css
Labels: Awaiting Review

#42 remove unnecessary code
  client/src/components/app/App.js
Labels: Awaiting Review, Urgent, bug

#43 Header logo component
  client/src/components/app/App.js
  client/src/components/utils/Header/HamburgerButton/index.js
  client/src/components/utils/Header/Menu/index.js
  client/src/components/utils/Header/Menu/style.css
Labels: Done

#44 fix typo/bug in props validation
  client/src/components/utils/Header/HamburgerButton/index.js
Labels: Done

#33 Footer component
  client/package-lock.json
  client/src/components/utils/anchor.js
  client/src/components/utils/footer/index.js
  client/src/components/utils/footer/style.css
  client/src/components/utils/index.js
Labels: Awaiting Review, Frontend

#47 Page not found 404
  client/src/components/pages/.gitkeep
  client/src/components/pages/PageNotFound/index.js
  client/src/components/pages/PageNotFound/style.css
Labels: Awaiting Review

#49 update the menu and fix bugs
  client/src/components/utils/Header/Menu/style.css
  client/src/components/utils/Header/index.js
Labels: Awaiting Review, bug

#34 Create Post
  client/src/components/pages/CreatePostPage/Event/index.js
  client/src/components/pages/CreatePostPage/Event/style.css
  client/src/components/pages/CreatePostPage/PublicServices/index.js
  client/src/components/pages/CreatePostPage/PublicServices/style.css
  client/src/components/pages/CreatePostPage/dumyData.js
  client/src/components/pages/CreatePostPage/index.js
  client/src/components/pages/CreatePostPage/style.css
  client/src/components/pages/index.js
  client/src/components/utils/DropDownAntd.js
  client/src/components/utils/InputAntd.js
  client/src/components/utils/TextAreaAntd.js
  client/src/components/utils/index.js
Labels: Awaiting Review
